### ISSUE TITLE
What about ssl?

### ISSUE THREAD

**Issue by deadtrickster** [fukamachi/dexador#1]
I glanced through code and it looks like dexador only supports client certificates. But what about
- Server certificate validation with ability to provide custom cafile/capath
- Hostname validation?

**Comment by fukamachi** [comment]
You can specifiy certificate file, key and password at `:ssl-cert--file`, `:ssl-key-file` and `:ssl-key-password`. It doesn't have a feature for validating hostnames yet.

**Comment by deadtrickster** [comment]
these options for client certificate. I'm talking about server certificate (chain) validation.

**Comment by fukamachi** [comment]
Not implemented yet.

**Comment by tmccombs** [comment]
Since dexador uses cl+ssl for ssl, you can use the following to enable ssl certificate verfication:

```lisp
(setf (cl+ssl:ssl-check-verify-p) t)
```

and then use `ssl-set-global-default-verify-paths` to use the default certificate chain and/or `use-certificate-chain-file` for custom certificate chains.

**Comment by fukamachi** [comment]
It was added at #30 by chance.
