### ISSUE TITLE
[macOS] Error: The alien function "SSL_get_peer_certificate" is undefined.

### ISSUE THREAD

**Issue by fukamachi** [fukamachi/dexador#105]
Failed test: https://github.com/fukamachi/qlot/runs/4494990296?check_suite_focus=true
Last successed test: https://github.com/fukamachi/qlot/runs/4459065945?check_suite_focus=true

**Comment by wmealing** [comment]
Seeing this too.

**Comment by fukamachi** [comment]
Probably fixed by https://github.com/cl-plus-ssl/cl-plus-ssl/pull/143.
