### ISSUE TITLE
connection cache is both thread unsafe and leaks sockets / connections

### ISSUE THREAD

**Issue by ajberkley** [fukamachi/dexador#106]
Rumor on reddit was that there is an outstanding bug in dexador that occurs when :use-connection-pool is t.  Advice was to just set :use-connection-pool nil.  But with default parameters that leaks socket streams because :keep-alive is t by default.

Anyway, I see several bugs in the connection cache and would like to fix them.  First, there is a race every time a new thread is used because you are writing to a hash-table without blocking readers (on CCL and Lispworks it might work, on sbcl this only works well if :synchronized is t).  Also the cache never removes streams and never closes sockets and does not share the cache between threads.  This doesn't work for long running processes and certainly not if you are talking to a large number of servers with many threads.  Plus there are cases where the streams are returned to the cache and to the user at the same time which can lead to disaster.  As Dexador is meant to be a general purpose library I think these sorts of things should be fixed.

In PR #107  I have a set of changes to how this is done to address the issues above:

1. Change cache to be an LRU cache shared among threads.  Close sockets when they are evicted.
2. When :keep-alive t :use-connection-pool nil handle case where user does not close the returned socket-stream
3. When :keep-alive t :use-connection-pool t :want-stream t return the stream to the pool when the user either finishes reading all expected data or closes the stream.
4. When user passes in a stream and we are redirected to a different server, do not re-use the original stream.

This is based on my understanding of the use of the 4th value and the :stream parameter.  Presumably the user can pass in a stream for us to use to try and talk to the client if they are doing external connection pool handling.  Or they can pass in the 4th value from a previous call with :keep-alive t to do a one element version of connection pooling (this is how simple connection re-use is handled in drakma and is an easy work flow --- but now it is just unnecessary work on the users part given the internal connection pool handling that gives the same effect).

This addresses issues #97, #92, and #87 and supersedes pull request #86 

Thank you for considering this!

**Comment by fukamachi** [comment]
Sorry for the delay.
I'm surprised that you investigated and made fixes in spite of the hard-to-read code.

Actually, I've been noticed these problems but couldn't make time to fix them.
I appreciate your efforts :)
