### ISSUE TITLE
There is no character with name "NUL"

### ISSUE THREAD

**Issue by fzn0x** [fukamachi/dexador#114]
I receive this error when calling dexador quickload.

```lisp
(ql:quickload "dexador")
```

Throws:
```sh
To load "dexador":
  Load 1 ASDF system:
    dexador
; Loading "dexador"
[package proc-parse]
*** - READ from #<INPUT BUFFERED FILE-STREAM CHARACTER #P"C:\\Users\\user\\quicklisp\\dists\\quicklisp\\software\\proc-parse-20190813-git\\src\\proc-parse.lisp" @359>: there is no character with name "NUL"
```

**Comment by fukamachi** [comment]
Lack of basic information. Please write the following:

* OS
* Lisp implementation (name and version)
* Quicklisp dist version
* Version (or git commit ref) of the library, if you installed it manually
  * In this case, Dexador and Proc-Parse

**Comment by fzn0x** [comment]
> Lack of basic information. Please write the following:
> 
> * OS
> * Lisp implementation (name and version)
> * Quicklisp dist version
> * Version (or git commit ref) of the library, if you installed it manually
>   
>   * In this case, Dexador and Proc-Parse

That is my first time using Lisp, really really lack how to describe it in Lisp community, I was figure out that is my Lisp version problem, I was using the latest and look like it didn't accept the `!#Nul` syntax.
