### ISSUE TITLE
dex:fetch leaves files open

### ISSUE THREAD

**Issue by Linden6** [fukamachi/dexador#118]
Sometimes when using dex:fetch I receive a 'too many open files' error.  This occurs when the number of files I am trying to download exceeds my number of open files limit ('soft' ulimit).  It would appear, therefore, that after saving the fetched files the file connection remains open.

If I modify dex:fetch by adding a close stream command at the end of it:
```
...
(with-open-file (out destination
                     :direction :output :element-type '(unsigned-byte 8)
                     :if-exists if-exists
                     :if-does-not-exist :create)
  (let ((body (apply #'dex:get uri :want-stream t :force-binary t
                     (remove-from-plist args :if-exists))))
    (alexandria:copy-stream body out)
    (close body)  ; <-- BY ADDING THIS
    ))))
```

then the 'too many open files' error doesn't appear.

It would appear, therefore, that a command to close the stream at this point is necessary for closing the file connection.

[I'm using SBCL 2.1.11.debian, dexador-20220220-git.]

**Comment by ajberkley** [comment]
Yes, that is indeed a bug!  When we use :want-stream t we need to close the stream when done with it.  Thank you!  I will patch this.

**Comment by ajberkley** [comment]
Actually the bug is in our keep-alive stream implementation... it is supposed to close these automatically.  will fix it there.

**Comment by Linden6** [comment]
Yes, I did notice this in the document string for dex:get:

_If WANT-STREAM is T, then a STREAM is returned as the first value.  You may read this as needed to get the body of the response.  If KEEP-ALIVE and USE-CONNECTION-POOL are T, then **the stream will be returned to the connection pool when you have rea**d all the data or closed the stream._

But setting KEEP-ALIVE and USE-CONNECTION-POOL to T, the stream isn't currently returned to the connection pool when all the stream data has been read.

Thanks

**Comment by ajberkley** [comment]
See https://github.com/fukamachi/dexador/pull/119
Letting the CI run

**Comment by ajberkley** [comment]
OK, so there was a bug in keep-alive streams when using read-sequence on them... they were forgetting to close the underlying fd.  That should fix your problem.  There was an additional bug that could have been hypothetically triggered if you call fetch with keep-alive nil, in which case I added an explicit close in fetch.

**Comment by Linden6** [comment]
Just compiled the changed _**keep-alive-stream.lisp**_, and error no longer occurs.  Many thanks the speedy resolution.
