### ISSUE TITLE
Potential issue with failing to close connections

### ISSUE THREAD

**Issue by K1D77A** [fukamachi/dexador#120]
I have my application which is deployed on my VPS the code is @ https://github.com/K1D77A/LunaMech
I have recently been having an issue where I run out of file descriptors and my application basically crashes (thrown into debugger for unhandled condition). Systemd ulimits and whatnot. 
Today I started the application and I have been monitoring my open files using `lsof` and the number of TCP connections has been slowly increasing. When I start the application there are about 5, now a few hours later there are over 40, here is a screenshot:
![image](https://user-images.githubusercontent.com/10334164/171040105-a243e43a-abdd-4dfe-b582-0720c44953f2.png)
I have tried using dex:clear-connection-pool but it has no effect.
I am am pretty sure this is a Dex problem as I use it in a few places in my code (checking for rss, polling jitsi, for interaction with matrix) and all of the file opening is done using with-open-file.
My VPS is running ubuntu with kernel 5.13.0-44 using SBCL 2.2.0.
Thanks.

**Comment by K1D77A** [comment]
After leaving it for one night this is the FD's open.
![image](https://user-images.githubusercontent.com/10334164/171190864-3afbccd7-cc16-4a61-8d1e-eec2b8ca9963.png)

I have checked the connection-pool which is empty, the :use-connection-pool nil was a hack to fix the previously broken connection pool, I will go through and change. 

Thanks for taking the time :+1:

**Comment by ajberkley** [comment]
Could you do me a really big favor and try pulling https://github.com/ajberkley/dexador.git and see if it solves your problem?

I am pretty sure this is 4xx and 5xx error handling related, as I was able to reproduce fd leakage using them and fixed it, but that doesn't really mean it is the problem you see.

**Comment by K1D77A** [comment]
Okay I tried it and it caused my new image to enter LDB.

![image](https://user-images.githubusercontent.com/10334164/171227381-90f5c342-8b04-4ca0-b8e2-c82a21d9bb53.png)

**Comment by K1D77A** [comment]
I will rebuild without your patched version and see if the crash goes away

**Comment by K1D77A** [comment]
Okay I rebuilt with your patch and restarted my VPS, it seems to be working. I'll update you in 30

**Comment by ajberkley** [comment]
Those two close-waits may be connections sitting in the connection cache that have been closed by the server after some timeout.  They will sit there forever until you try and use them, at which point the code will see they are closed and close the streams.  You can try clear-connection-cache now to see if that is the case, or inspect the cache itself...

The LDB issue looks kind of scary... did you get any information from it?  I'd be surprised if anything in dexador can cause that problem (except maybe CL+SSL stuff, but that also seems unlikely)... I gather it didn't happen again?

**Comment by K1D77A** [comment]
When I stopped my app, rebuilt with your patch, uploaded and started I was thrown in LDB. 
When I stopped that failed app, rebuilt without your patch, uploaded and started SBCL exited with code 'exit' (something like that). 
After a VPS restart there were no problems... beats me.

I tried clear-connection-pool and that worked fantastically. Thanks :+1:

**Comment by ajberkley** [comment]
Merged #123 which fixes this

**Comment by K1D77A** [comment]
Thanks for your quick help :)
