### ISSUE TITLE
`ignore-and-continue` on `http-request-fail`

### ISSUE THREAD

**Issue by aadcg** [fukamachi/dexador#127]
I'm on SBCL, and I noticed that the following never returns.

```lisp
(handler-bind ((dex:http-request-failed #'dex:ignore-and-continue))
  (dex:get "https://en.wikipedia.org/wiki/Gianmarco_A"))
```

It seems that it stems from the fact that `(dex:get "https://en.wikipedia.org/wiki/Gianmarco_A")` enters a loop when choosing `ignore-and-continue`. 

Is it a bug, or is there a way to simply continue when the request fails once?

**Comment by ajberkley** [comment]
(handler-bind ((dex:http-request-failed (dex:retry-request 2 :interval 1))
 (dex:get "https://en.wikipedia.org/wiki/Gianmarco_A"))

will try twice with a sleep of 1 second between tries and then will decline to handle the error.

**Comment by aadcg** [comment]
It seems it's not working for me. Am I doing something terribly wrong? See the gif below. 

![output-2022-06-20-22:21:40](https://user-images.githubusercontent.com/45483512/174679436-5753b187-b6f7-4308-a5b8-447c0fa1a191.gif)

**Comment by aadcg** [comment]
I understood it. I was actually looking for the following:

```lisp
(handler-case (dex:get "https://en.wikipedia.org/wiki/Gianmarco_A")  
  (dex:http-request-failed (e)
    (format *error-output* "The server returned ~D" (dex:response-status e))))
```
