### ISSUE TITLE
Automatic URL parameter encoding for Content-Type: application/x-www-form-urlencoded breaks old code

### ISSUE THREAD

**Issue by Jach** [fukamachi/dexador#130]
Hi, after pulling the current quicklisp version of Dexador I saw a test failure in my [project](https://github.com/Jach/cl-ses4). I used git-bisect and found the breaking commit was https://github.com/fukamachi/dexador/commit/1fa55b3c4d062cabe430bc5ad7463f3dfab1b69c

The underlying issue is that I'm calling `dex:post` with my own explicit headers alist with a specified content-type of "application/x-www-form-urlencoded", and my own explicit content alist which I have already called `quri:url-encode-params` on, so the content passed down to dex is just a string. The commit above changes the logic in [usocket.lisp](https://github.com/fukamachi/dexador/blob/master/src/backend/usocket.lisp#L549) so that `form-urlencoded-p` is true, which causes its `content` binding a few lines down to try and automatically encode the params. Since I already encoded them, I get the error "QURI.ENCODE::PARAMS-ALIST is "Action=SendEmail&Source=...", which is not of type LIST.".

I can fix this on my side by just passing my un-encoded content alist instead of the encoded version. But I wonder if you might consider this a bug in dexador or quri instead? Or maybe not a bug per se but willing to consider some defensive changes to make this usage that was previously valid remain valid. For example, the line in usocket.lisp could check that content is a list before trying to encode it, and just leave it alone if it's not a list. (Keeping quri's own API contract about expecting a list seems right.)

**Comment by ajberkley** [comment]
Sorry about the lack of response and for breaking your library.  Fukamachi seems unavailable and I've been filling in as maintainer, but I haven't had much time to work on things.  As I understand it you would like a change like below in usocket.lisp (winhttp.lisp should be fine as far as I can tell, though I didn't test it):

(content (if (and form-urlencoded-p (not (stringp content))) ;; user can provide already encoded content

Does that make sense?

**Comment by Jach** [comment]
No worries on delay, I saw Fukamachi's status update, thanks for stepping up!

Your proposal makes sense and I think would be decent. A bit of renaming of this `let*` form's `content` to distinguish it from the function's original `content` param might be useful for clarity, too.

I haven't tested in Windows either, but briefly looking at winhttp.lisp I think there would be a bug as well, but a different one. That file has a `convert-content` function which first checks the type of `content` and, seeing it's a string, skips the possibility of re-encoding it. However it would create a new issue because it decides that the content-type is "text/plain", and even overrides the user-provided explicit content type in the passed headers with that. (Also assuming that converting the string to octets doesn't cause a problem, maybe it's needed for Windows?) This maybe points at a larger issue, like the only way to send e.g. a JSON request through the Windows path would be to encode the content as a u8 array first?

**Comment by ajberkley** [comment]
I think you are right about the windows side, see #135... I don't have a window machine so am not so eager to dive into it.  I will submit the simple change above without changing variable names (though I share your general sense that dexador could use some clean-up).

**Comment by ajberkley** [comment]
Fixed by #136
