### ISSUE TITLE
Calling DEX::MAYBE-CLOSE with optional "close-if T" argument causes a CCL::BAD-SLOT-TYPE

### ISSUE THREAD

**Issue by iukibkim** [fukamachi/dexador#131]
Hi, I've been using Dexador to download some files and I've been having issues on Clozure CL.
Any requests which use  `:want-stream t` fail with a `CCL::BAD-SLOT-TYPE` condition inside `(dex::maybe-close stream t)`

`dex:fetch` uses `:want-stream t` internally:
https://github.com/fukamachi/dexador/blob/398241fe3f61f0546606712f2e9e40201dbee55a/src/dexador.lisp#L124

This is on the latest QuickLisp dist as of writing "2022/07/08".
```lisp
Clozure Common Lisp Version 1.12.1  LinuxX8664

For more information about CCL, please see http://ccl.clozure.com.

CCL is free software.  It is distributed under the terms of the Apache
Licence, Version 2.0.
? (ql:quickload :dexador)
To load "dexador":
  Load 1 ASDF system:
    dexador
; Loading "dexador"
.
(:DEXADOR)
? (dex:fetch "https://archive.org/download/SuicideQueen/SuicideQueen.png" "/tmp/test.jpg" :if-exists :supersede)
> Error: The value NIL can not be used to set the value of the slot STREAM in #<DEXADOR.KEEP-ALIVE-STREAM:KEEP-ALIVE-STREAM #x302001F43A3D>, because it is not of type STREAM.
> While executing: CCL::%MAYBE-STD-SETF-SLOT-VALUE-USING-CLASS, in process listener(1).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.
1 > 
```

The above works fine on SBCL:
```lisp
This is SBCL 2.1.11.debian, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* (ql:quickload :dexador)
To load "dexador":
  Load 1 ASDF system:
    dexador
; Loading "dexador"
.......
(:DEXADOR)
* (dex:fetch "https://archive.org/download/SuicideQueen/SuicideQueen.png" "/tmp/test.jpg" :if-exists :supersede)
NIL
```

Looking at the code this line is the culprit:
https://github.com/fukamachi/dexador/blob/398241fe3f61f0546606712f2e9e40201dbee55a/src/keep-alive-stream.lisp#L55-L58

It looks like a issue where SBCL allows typed class slots to be set to `nil`, where CCL doesn't.
https://github.com/fukamachi/dexador/blob/398241fe3f61f0546606712f2e9e40201dbee55a/src/keep-alive-stream.lisp#L19-L25

I wasn't sure if I should take this here or to the CCL github, please let me know.

**Comment by ajberkley** [comment]
This is a dexador bug.  If you would like to submit a PR, please just change :type stream to :type (or null stream).

**Comment by ajberkley** [comment]
(or if not, I can make the change too, but I don't have CCL installed so I would just be flying blind)

**Comment by ajberkley** [comment]
I created a PR and will merge it to fix this once the CI finishes, no need for you to do it.  Thank you for reporting the bug!

**Comment by iukibkim** [comment]
I've tested the change locally and it resolves the issue. Thanks!
