### ISSUE TITLE
Windows: Content-Type is replaced with "text/plain" when `:content` is present

### ISSUE THREAD

**Issue by samuel-hunter** [fukamachi/dexador#135]
Forms to reproduce on SBCL on Windows:
```lisp
(require :dexador)
;; Tested with both :method :get and :method :post
;; httpbin responds with a JSON payload of the request data
(dexador:request "https://httpbin.org/anything" :method :get 
                 :headers '((:content-type "application/json")) :content "{}")
```

If *content* is present with a string, then the request is sent with the header `Content-Type: text/plain`, even though this is specified to be `Content-Type: application/json`. When *content* is removed, the request is sent with the header `Content-Type: application/json`.

I've found this bug on Windows. On Linux, both forms send a request with header `Content-Type: application/json` as expected.

Just a note on reproducing this bug, I had to apply this PR https://github.com/usocket/usocket/pull/89 to Quicklisp's latest version of usocket; otherwise, it would fail to compile on Windows.

Thanks!

**Comment by ajberkley** [comment]
I would appreciate a PR to fix this as I don't have a windows machine to develop on.

**Comment by fukamachi** [comment]
How about changing the `:headers` to `'((:content-type . "application/json"))`?

**Comment by fukamachi** [comment]
I could reproduce it on my machine. I'll look into this.
