### ISSUE TITLE
PARAMETERS keyword argument alternative

### ISSUE THREAD

**Issue by chiku-samugari** [fukamachi/dexador#14]
What is the proper way to replace PARAMETERS keyword argument of DRAKMA:HTTP-REQUEST when I use GET method?

**Comment by fukamachi** [comment]
Dexador has not a complete alternative for it as I'm not sure if building an URI is a responsibility of HTTP client library.

Why don't use `quri:make-uri` or `quri:copy-uri`?:

```common-lisp
(dex:get (quri:make-uri :scheme "http"
                        :host "b.hatena.ne.jp"
                        :path "/"
                        :query (quri:url-encode-params '(("name" . "Eitaro Fukamachi")))))
```

```common-lisp
(dex:get (quri:copy-uri (quri:uri "http://b.hatena.ne.jp/")
                        :query (quri:url-encode-params '(("name" . "Eitaro Fukamachi")))))
```

**Comment by chiku-samugari** [comment]
Thanks for the quick response. The second one seems to be a good alternative.
