### ISSUE TITLE
Specifying content types for parts of a post request

### ISSUE THREAD

**Issue by prxq2** [fukamachi/dexador#147]
Hi,

if one were to send a multipart/mixed message using dexador, currently it is not possible to specify the types of the single parts. Is there something planed along these lines?

If not, I'm wondering if one could extend the interface as follows:

 (dex:post "http://example.com/service"
          :headers '(("content-type" . "multipart/mixed"))
	  :content  '((("data" :type :json) . "{foo: 1, bar: 2")
		      ("photo" . #p"/home/prxq2/baz.jpg")))

i.e. extend the key to be a optionally a cons and handle accordingly. Do you think this is a reasonable option? If so I could do that and send a patch.

What do you think?

Regards,
            Mario

**Comment by fukamachi** [comment]
It'd be great to allow multipart/mixed requests. I'm not sure what interface is acceptable.
