### ISSUE TITLE
Copying from KEEP-ALIVE-STREAM: The value NIL is not of type STREAM

### ISSUE THREAD

**Issue by samuel-hunter** [fukamachi/dexador#150]
I want to download a resource to a file. Fetching the request all-in-one and writing the sequence to the file stream works, however if I add `:want-stream t` and copy the request stream to the file stream I get an error:

```lisp
(defun download-via-sequence ()
  (with-open-file (out #P"600x400-orange-white.png"
                       :direction :io
                       :element-type '(unsigned-byte 8))
    ;; This works fine
    (write-sequence
      (dexador:get "https://placehold.co/600x400/orange/white.png")
      out)))

(defun download-via-stream ()
  (with-open-file (out #P"600x400-orange-white.png"
                       :direction :io
                       :element-type '(unsigned-byte 8))
    (with-open-stream (res (dexador:get "https://placehold.co/600x400/orange/white.png"
                                        :verbose t
                                        :want-stream t))
      ;; Fails on here!
      (uiop:copy-stream-to-stream res out
                                  :element-type '(unsigned-byte 8)))))
```

As a workaround, if I replace `dexador:get` with `drakma:http-request`, or I add the argument `:keep-alive nil`, the toplevel function works as expected.

Here is the backtrace:

```lisp
Backtrace:
  0: ((:METHOD NO-APPLICABLE-METHOD (SB-GRAY::STREAM-FUNCTION)) #<SB-GRAY::STREAM-FUNCTION COMMON-LISP:OPEN-STREAM-P (9)> NIL) [fast-method]
  1: (SB-PCL::CALL-NO-APPLICABLE-METHOD #<SB-GRAY::STREAM-FUNCTION COMMON-LISP:OPEN-STREAM-P (9)> (NIL))
  2: ((LAMBDA (DEXADOR.BACKEND.USOCKET::UNDERLYING-STREAM ABORT) :IN DEXADOR.BACKEND.USOCKET:REQUEST) NIL #<unused argument>)
      in .local/share/roswell/lisp/quicklisp/dists/quicklisp/software/dexador-20230214-git/src/backend/usocket.lisp line 795
    Locals:
      DEXADOR.BACKEND.USOCKET::UNDERLYING-STREAM = NIL
      DEXADOR.BACKEND.USOCKET::URI = #<QURI.URI.HTTP:URI-HTTPS https://placehold.co/600x400/orange/white.png>
      }}}
  3: ((FLET "CLEANUP-FUN-0" :IN UIOP/STREAM:COPY-STREAM-TO-STREAM)) [cleanup]
  4: (UIOP/STREAM:COPY-STREAM-TO-STREAM #<DEXADOR.KEEP-ALIVE-STREAM:KEEP-ALIVE-STREAM {10059AD9E3}> #<SB-SYS:FD-STREAM for "file /home/shunter/600x400-orange-white.png" {10059C0683}> :ELEMENT-TYPE (UNSIGNED..
      No source line information
    Locals:
      #:G7 = (UNSIGNED-BYTE 8)
      #:G8 = NIL
      INPUT = #<DEXADOR.KEEP-ALIVE-STREAM:KEEP-ALIVE-STREAM {100198E1F3}>
      LINEWISE = NIL
      OUTPUT = #<SB-SYS:FD-STREAM for "file /home/shunter/600x400-orange-white.png" {10019FF1B3}>
      PREFIX = NIL
      }}}
  5: (BAR)
    Locals:
      OUT = #<SB-SYS:FD-STREAM for "file /home/shunter/600x400-orange-white.png" {10019FF1B3}>
      RES = #<DEXADOR.KEEP-ALIVE-STREAM:KEEP-ALIVE-STREAM {100198E1F3}>
```

Frame 2 points to Line 795 of `src/backend/usocket.lisp`:
```lisp
(lambda (underlying-stream abort)
  (declare (ignore abort))
  ;; ***HERE***
  (when (open-stream-p underlying-stream)
    ;; read any left overs the user may have not read (in case of errors on user side?)
    (loop while (ignore-errors (listen underlying-stream)) ;; ssl streams may close
          do (read-byte underlying-stream nil nil))
    (when (open-stream-p underlying-stream)
      (push-connection (format nil "~A://~A"
                               (uri-scheme uri)
                               (uri-authority uri)) underlying-stream #'close))))
```

So it would pass this lambda to `#'CONVERT-BODY`, which in turn passes it as the close-action to the keep-alive stream. This function would presumably be called on EOF, at which point it somehow loses its underlying stream.

**Comment by ajberkley** [comment]
Thank you for reporting this.  I will take a look.

**Comment by ajberkley** [comment]
uiop:copy-stream-to-stream calls close-stream on the input stream when it is done (it uses with-open-stream).  So you requested a keep-alive stream, which means you intend to give it back to dexador for use later, but then you call close on it.  I am not sure this shouldn't be an error to do.

Do you have a suggestion for what you would want behavior to be?  I think it probably shouldn't error, and I'm wary of randomly adding spammy warning messages.

**Comment by samuel-hunter** [comment]
> uiop:copy-stream-to-stream calls close-stream on the input stream when it is done (it uses with-open-stream). So you requested a keep-alive stream, which means you intend to give it back to dexador for use later, but then you call close on it. The same is done by the with-open-stream in your example code. I am not sure this shouldn't be an error to do.

Is that correct behavior? When I run this expression:

```lisp
(let ((res (dex:get "https://placehold.co/600x400/orange/white.png"
                    :want-stream t)))
  (close res)
  (open-stream-p res))
```

I get no exception raised. (However, the expression does return `T`, which should be false, as it should have been closed right before)

---

> Do you have a suggestion for what you would want behavior to be? I think it probably shouldn't error, and I'm wary of randomly adding spammy warning messages.

In the README, it says:

> want-stream (boolean)
>
>    A flag to get the response body as a stream.

I would expect the stream received to be an interface for the response body alone, not the stream of all requests within a single socket connection. Keeping faithful to this even when it's underlying a keep-alive stream would mean code (such as `uiop:copy-stream-to-stream`) wouldn't have to "know" that EOF isn't a "true" EOF, and less changes would have to be made when switching the `:keep-alive` argument.

Having to create a function within my system that copies all the behavior of a library function, line for line, except for one change, doesn't feel like good engineering.

**Comment by ajberkley** [comment]
Yeah, you are right.  I had forgotten how this is actually implemented.  It is actually fine to call close on the keep-alive-stream.  This is just a bug.  Will fix.

**Comment by ajberkley** [comment]
Fix committed!  Thank  you!

**Comment by samuel-hunter** [comment]
Verified the fix works, thanks!
