### ISSUE TITLE
When specifying content-type for multipart/mixed, the value must be a string

### ISSUE THREAD

**Issue by Shinmera** [fukamachi/dexador#167]
When performing a request like:

```lisp
(dex:request "..." :method :post :headers `(("content-type" . "multipart/mixed"))
                   :content `(("var" ,(make-array 1 :element-type '(unsigned-byte 8)) :content-type "application/octet-stream")))
```

Dexador fails, since the value is not a string. However, for binary payloads like this, it's not possible to use a string as the binary cannot be utf-8 encoded. It would also be nice if one could pass pathnames in addition to octet arrays.

**Comment by ajberkley** [comment]
OK, will do!  I thought pathnames already worked.

**Comment by ajberkley** [comment]
See #168 --- does this do what you want?

**Comment by Shinmera** [comment]
Yep! Fixes my problem, thank you very much!

**Comment by ajberkley** [comment]
Merged slightly fixed up version

**Comment by Shinmera** [comment]
Thanks a lot for your work!
