### ISSUE TITLE
Is this cross implementation ?

### ISSUE THREAD

**Issue by vindarel** [fukamachi/dexador#27]
Hi,
I'm doing advertising for dexador and I'm being asked: does dexador work on ABCL, CLISP, SBCL, ECL (or a lisp in that family), and CCL? I can't find that information.

Thanks ! cheers

**Comment by fukamachi** [comment]
I tested it with SBCL, ABCL, ECL and CCL.
Since Dexador uses usocket as its backend, I expect it's portable enough like Drakma.

**Comment by vindarel** [comment]
Thanks !
