### ISSUE TITLE
Master branch fixes SSL issue

### ISSUE THREAD

**Issue by pebblexe** [fukamachi/dexador#31]
I was getting these errors:
X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN
X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY
and after cloning the master-branch to quicklisp/local-projects they went away.

Just posting this in case anyone else gets stuck.

**Comment by fukamachi** [comment]
`(ql:update-dist "quicklisp")` is enough for it since the current master branch is included in the latest Quicklisp dist (2017-02-27).
