### ISSUE TITLE
HTTPS request hangs

### ISSUE THREAD

**Issue by nulldatamap** [fukamachi/dexador#33]
Example:
```lisp
(dex:get "https://api.github.com/")
```

This simply hangs, if I interrupt the process, the backtrace looks like:

```lisp
Backtrace:
  0: (SB-THREAD:THREAD-YIELD) [external]
  1: (SB-SYS:WAIT-UNTIL-FD-USABLE 400 :INPUT NIL T)
  2: (CL+SSL:MAKE-SSL-CLIENT-STREAM #<unavailable argument> :CERTIFICATE #<unavailable argument> :KEY #<unavailable argument> :PASSWORD #<unavailable argument> :METHOD #<unavailable argument> :EXTERNAL-FOR..
  3: (CL+SSL::CALL-WITH-GLOBAL-CONTEXT #.(SB-SYS:INT-SAP #X07444650) T #<CLOSURE (LAMBDA NIL :IN DEXADOR.BACKEND.USOCKET:REQUEST) {1008B453AB}>)
  4: (DEXADOR.BACKEND.USOCKET:REQUEST #<unavailable argument> :METHOD :GET)
```

I'm on Win7 x64, SBCL 1.3.15, OpenSSL 1.0.2g  1 Mar 2016, using the quicklisp distribution of Dexador (version 0.9.10).

**Comment by fukamachi** [comment]
Thank you for reporting.
However, I cannot reproduce it on Windows 10 & SBCL 1.3.15.
I suppose the hang is because of waiting for the HTTP response. I'm not sure why.

**Comment by mtstickney** [comment]
I experienced this issue trying to use a newer version of qlot. The hang seems to be specific to SBCL, as CCL reports an error:
````
> Error: The TLS/SSL connection on handle #<A Foreign Pointer #x2A30858> has been closed (return code: 5).
>        SSL error queue is empty.
````

I've checked, and drakma is able to make the same request successfully (dexador succeeds on my linux host, too). The chief difference seems to be that drakma is using `cl+ssl:stream-fd` and passing the result to `make-ssl-client-stream`, rather than passing the stream directly (but I'm not sure if that's meaningful).

I'll check on my Windows 10 machine when I get home tonight, to see if this works correctly there.

**Comment by mtstickney** [comment]
Correction: the real difference is that the version of drakma in quicklisp doesn't create an ssl context. Removing the `cl+ssl:with-global-context` code from dexador makes it work correctly in CCL.

Presumably this has something to do with certificate verification (but dexador does fail when you set `:insecure t`). I'll investigate more, and maybe check the tip version of drakma, which does use an ssl context.

**Comment by mtstickney** [comment]
Drakma tip has this problem too, so it seems like it's a problem with cl+ssl on windows when using contexts.

**Comment by mtstickney** [comment]
I've filed an [issue](https://github.com/cl-plus-ssl/cl-plus-ssl/issues/50) upstream with cl+ssl about this, if you want to follow it there.

**Comment by tshatrov** [comment]
I had the same bug and can confirm that updating to the latest cl+ssl version from quicklisp fixes this issue.

**Comment by mattboroi** [comment]
@ajberkley this might be able to be closed, the upstream issue is closed and i'm unable to reproduce the same experience.

windows 10 (22h2); sbcl 2.2.10; cl+ssl-20221106-git; OpenSSL 1.1.1q  5 Jul 2022
