### ISSUE TITLE
can't save a cookie.

### ISSUE THREAD

**Issue by ta2gch** [fukamachi/dexador#4]
Now I try to make an ask.fm client `ezoe`.

To ask someone, we needs an ask.fm account.

Following code login to ask.fm.

I expect `dexador` that

1. first, `dex:get` access to "ask.fm/login" 
2. get `authenticity_token` and `_ask.fm_session ` cookie. from body
3. and keep a connection.
4. next, `dex:post` access to "ask.fm/session" with `authenticity_token`'s value (from '2'), `username` ,  `password` and  `_ask.fm_session` cookie.
5. `dex:post` save `auth_token="foobarhogefuga..."` to cookie. 

but, dex:get couldn't keep `_ask.fm_session`'s cookie and save `auth_token` to cookie.

In Firefox, at first, `auth_token` is initialize with `""`. 
next set a value (like "foobarhogefuga...").
`dexador` is only initialize..

`dexador` saticefies my expectation?

thanks.
```lisp
(ql:quickload
 '(:dexador
   :cl-cookie
   :cl-html-parse
   :get-element-by
   :quri))

(defun login (user password)
  (let* ((url "http://ask.fm")
	 (cookie (cl-cookie:make-cookie-jar))
	 (header '(("User-Agent" . "Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0")))
	 (body (dex:get url :cookie-jar cookie
			    :headers header
			    :keep-alive t
			    :verbose t))
	 (tree (html-parse:parse-html body))
	 (form (geby:get-element-by
		:name "authenticity_token" tree))
	 (token (quri:url-encode (getf (cdar form) :value)))
	 (params`(("authenticity_token" . ,token)
		  ("login"              . ,user)
		  ("password"           . ,password)
		  ("commit"             . "ログイン"))))
    (print cookie)
    (dex:post "http://ask.fm/session"
	      :cookie-jar cookie
	      :headers header
	      :content params
	      :keep-alive t
	      :verbose t)
    (print cookie)))
```

```

**Comment by ta2gch** [comment]
this code depends on [geby:get-element-by](https://github.com/ta2gch/get-element-by)

**Comment by fukamachi** [comment]
Thank you for reporting.

I found it's a bug of cl-cookie that cl-cookie sometimes couldn't match the cookie if Path existed.
I believe it has been fixed at https://github.com/fukamachi/cl-cookie/commit/cea55aed8b9ad25fafd13defbcb9fe8f41b29546 and https://github.com/fukamachi/dexador/commit/79a27511907d670e3c303b41b3d0335ae2ca20b6.

Could you please try it again after updating those repositories?

**Comment by fukamachi** [comment]
This is not related to the bug, however you must not `quri:url-encode` the authenticity_token because Dexador encodes the content into a urlencoded string if it's an association list.

**Comment by ta2gch** [comment]
Thank you for support.
I understood about `qrui:url-encode`.

I tried to use `dexador` and `cl-cookie` with latest version.
I checked `cl-cookie` works well. :)
