### ISSUE TITLE
The function quri.parser::parse-scheme-string is undefined.

### ISSUE THREAD

**Issue by vindarel** [fukamachi/dexador#61]
Hi,
I suddenly have this error on a simple `dex:get`.

    The function quri.parser::parse-scheme-string is undefined.

What's going on ? I don't find where this function appears. I'm on Quicklisp 20180328. Looking at dexador in quicklisp's directory, an `rgrep` doesn't find parse-scheme-string.

I think this error appeared when I tried to upgrade QL but finally downgraded to this version (due to a Slime error).

**Comment by fukamachi** [comment]
The function is since 2014.
What implementation are you using?
2018年10月28日(日) 0:32 vindarel <notifications@github.com>:

**Comment by vindarel** [comment]
SBCL 1.2.4 Debian

Is there any preventive manipulation I can do ? (deleting fasl files here and there ? I tried some).

What I don't understand is where does the symbol `parse-scheme-string` come from, because it only appears once in the repository, and why it worked and it stopped working…

Longer stack trace:

```
  0: ("undefined function")
  1: (quri.parser::parse-uri-string #<unavailable argument> :start #<unavailable argument> :end #<unavailable argument>)
  2: (quri.uri:uri "http://1337x.to/sort-search/sintel/seeders/desc/1/" :start 0 :end nil)
  3: (dexador.backend.usocket:request #<unavailable argument> #<unavailable &REST argument> :method #<unused argument> :version #<unused argument> :content #<unavailable argument> :headers #<unavailable ar..
```

**Comment by vindarel** [comment]
Closing, since this isn't a Dexador bug. But damn !
