### ISSUE TITLE
Add `force-string` option

### ISSUE THREAD

**Issue by lambdadog** [fukamachi/dexador#63]
There are many cases where one might prefer to return a string even if the Content-Type isn't `text/*`

It's trivial to add a conversion afterwards so it's not a huge issue, but if `force-binary` exists it makes sense for `force-string` to exist too.

**Comment by fukamachi** [comment]
In that case, it cannot tell which encoding to convert to a string.
It's okay to use the default encoding like UTF-8, however, `babel:octets-to-string` could cause an error when some garbages in the data.

**Comment by beta-phenylethylamine** [comment]
I'd imagine allowing `force-string` to be set to either `nil`, `t`, or an encoding would work, and if it was set to `t`, just use babel's `*default-character-encoding*` (used by default when calling babel:octets-to-string -- defaults to `:utf-8`), no?

**Comment by fukamachi** [comment]
I agree that the kind of feature is useful now.
But, I'm wondering that adding a new option `:force-string` is the best for it.
There're already `:force-binary` and `:want-stream` for specifying the response type, so it may be combined, I guess.
