### ISSUE TITLE
get: special chars in url string are not converted, results in 400 bad request

### ISSUE THREAD

**Issue by mihaiolteanu** [fukamachi/dexador#67]
A call like
`(dexador:get "https://www.last.fm/music/Mötley+Crüe")`

results in 

> An HTTP request to "https://www.last.fm/music/Mötley+Crüe" returned 400 bad request.
   [Condition of type HTTP-REQUEST-BAD-REQUEST]

I'm assuming the special chars ö and ü, in this case, are not converted so that the call is not converted automatically to
`(dexador:get "https://www.last.fm/music/M%C3%B6tley+Cr%C3%BCe")`

which would be a call to the correct page.

curl seems to be doing this, as well as the browser before actually sending the request.

I'm not sure if this should be something dexador should handle or if it should be something the user needs to take care of. If the second, any nice, clean suggestions for how the user should handle this conversion?

**Comment by mihaiolteanu** [comment]
Ok, so here's a solution for user-side conversion of url's special chars.
There is a library, do-urlencode, for coding/decoding of urls.
For the example above, I only need to encode the last url component, otherwise the slashes will also be encoded, among other chars, and dexador doesn't handle that well, it seems.

`(ql:quickload :do-urlencode)`
`(dexador:get (format nil "https://www.last.fm/music/~a" (do-urlencode:urlencode "Mötley+Crüe")))`

**Comment by jonatack** [comment]
You can also use Quri (https://github.com/fukamachi/quri) which I believe is already loaded by Dexador.

```common-lisp
(dexador:get (format nil "https://www.last.fm/music/~a" (quri:url-encode "Mötley+Crüe")))
```

or

```common-lis
(setq path (format nil "/music/~a" (quri:url-encode "Mötley+Crüe")))
(dexador:get uri)
```

**Comment by jonatack** [comment]
You can also encode with `quri:url-encode` in Quri (https://github.com/fukamachi/quri) which I believe is already loaded by Dexador and perhaps faster:

```common-lisp
(dexador:get (format nil "https://www.last.fm/music/~a" (quri:url-encode "Mötley+Crüe")))
```

or building the URI with `quri:make-uri`:

```common-lisp
(setq path (format nil "/music/~a" (quri:url-encode "Mötley+Crüe")))

**Comment by jonatack** [comment]
You can also encode with `quri:url-encode` in Quri (https://github.com/fukamachi/quri) which I believe is already loaded by Dexador and perhaps faster:

```common-lisp
(dexador:get (format nil "https://www.last.fm/music/~a" (quri:url-encode "Mötley+Crüe")))
```

or building the URI with `quri:make-uri`:

```common-lisp
(setq path (format nil "/music/~a" (quri:url-encode "Mötley+Crüe")))

(dexador:get (quri:make-uri :scheme "https" :host "www.last.fm" :path path))
```
