### ISSUE TITLE
winhttp issues on Windows

### ISSUE THREAD

**Issue by tshatrov** [fukamachi/dexador#85]
I had Dexador from 2019-02-02 installed from Quicklisp and it served me well. Today I upgraded to the new version, which apparently uses winhttp instead of cl+ssl (which I had zero problems installing on Windows).

The first thing I noticed is that timeouts are unreasonably short. After bumping `*default-connect-timeout*` and `dexador:*default-read-timeout*` to 10000, I was actually able to do something, but with the default value of 10 I've been getting winhttp timeout on any non-trivial POST requests. Could these values be in milliseconds instead of seconds as opposed to cl+ssl?

Also the very first example `(dex:get "http://lisp.org/")` doesn't work for me, resulting in

```
ERROR 12175: Secure failure
   [Condition of type WINHTTP::WIN-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {1004FB9D73}>)

Backtrace:
  0: (WINHTTP::GET-LAST-ERROR)
  1: (WINHTTP:SEND-REQUEST #.(SB-SYS:INT-SAP #X009146C0) #() :START 0 :END NIL)
  2: (DEXADOR.BACKEND.WINHTTP:REQUEST #<QURI.URI.HTTP:URI-HTTPS https://lisp.org/> :MAX-REDIRECTS 4 :METHOD :GET :METHOD :GET)
  3: (DEXADOR.BACKEND.WINHTTP:REQUEST "http://lisp.org/" :METHOD :GET)
  4: (SB-INT:SIMPLE-EVAL-IN-LEXENV (DEXADOR:GET "http://lisp.org/") #<NULL-LEXENV>)
  5: (EVAL (DEXADOR:GET "http://lisp.org/"))
```
There might be something with this specific site's certificate but I'm not sure what. It uses Let's Encrypt just like my own site http;//ichi.moe which does work.

Overall I wish there was a way to continue using CL+SSL even on Windows if it's installed. I couldn't find such option in the code since using winhttp seems to depend on `:windows` feature.

**Comment by fukamachi** [comment]
You're right. It should be in miliseconds.

https://docs.microsoft.com/en-us/windows/win32/api/winhttp/nf-winhttp-winhttpsettimeouts

> Overall I wish there was a way to continue using CL+SSL even on Windows if it's installed.

Still you can use it with `dexador/backend/usocket:request`.
