### ISSUE TITLE
WANT-STREAM unsafely returns stream to connection pool

### ISSUE THREAD

**Issue by daewok** [fukamachi/dexador#87]
When `want-stream` and `use-connection-pool` are both true, the stream is returned to the pool before the returned stream has been completely read from. This can result in an error if a second request to the same server is sent before the caller has completely read the stream.

This is definitely a corner case, but, I think, still within the realm of something that's reasonable to want. As an example, this function signals an error that the stream is closed before it finishes reading it.

```
(defun uh-oh ()
  (let ((stream-1 (dex:get "http://example.com" :want-stream t))
        (stream-2 (dex:get "http://example.com" :want-stream t)))
    (loop
      :for line := (read-line stream-1 nil :eof)
      :until (eql line :eof)
      :do (print line))))
```
A more realistic example would be a multi-threaded program that performs HTTP requests on one thread and passes the streams to another thread for processing.

I'm handling this in my own connection pool on top of Dexador by requiring that the user `close` the returned stream when they're done with it. The close method then reads from the underlying stream to its EOF before returning it to the pool. Happy to share my code for that once I bang on it a bit more (most likely next weekend).

**Comment by ajberkley** [comment]
This is fixed now.
