### ISSUE TITLE
Connection stream is not closed properly in request function

### ISSUE THREAD

**Issue by alexnygren** [fukamachi/dexador#92]
When using dexador on Linux (Ubuntu 20.04) with SBCL 2.0.9, SBCL will promptly crash on the second POST request made with a return code of 141 and when using :content.   This seems to be because the stream handle doesn't seem to be properly closed, either in this form, or in the (finalize-connection) function, perhaps due to the if logic there.  I was able to fix it for my purposes by explicitly closing the stream in the final unwind-protect:
```
(unwind-protect
                    (let ((body (convert-body body
                                              (gethash "content-encoding" response-headers)
                                              (gethash "content-type" response-headers)
                                              content-length
                                              transfer-encoding-p
                                              force-binary
                                              force-string
                                              (connection-keep-alive-p
                                               (gethash "connection" response-headers)))))
                      ;; Raise an error when the HTTP response status code is 4xx or 50x.
                      (when (<= 400 status)
                        (with-restarts
                          (http-request-failed status
                                               :body body
                                               :headers response-headers
                                               :uri uri
                                               :method method)))
                      (return-from request
                        (values body
                                status
                                response-headers
                                uri
                                (when (and keep-alive
                                           (not (equalp (gethash "connection" response-headers) "close")))
                                  stream))))
		 (close stream)  ;; added explicit stream here*********
                 (finalize-connection stream (gethash "connection" response-headers) uri))
```

**Comment by fukamachi** [comment]
Thank you for reporting.
Can you paste the error message and stack traces here?
For the moment, adding `:keep-alive t` to the arguments might work as a workaround.

**Comment by alexnygren** [comment]
Unfortunately I don't get any stack traces or error messages, beyond SBCL terminating immediately with a return code 141.  There is no chance to enter the debugger to poke around and see what's happening.  It's like a core dump but no core file. Never seen SBCL do this, and so this may be tickling an underlying SBCL issue too. 

The cycle that I found was the first post there were no issues.  The second post would not complete (on Linux, not on macOS though) and the whole Lisp image would die.  I isolated the point of failure to the **finish-output** call to to the following line in request:  

` (when chunkedp
                   (setf (chunga:chunked-stream-output-chunking-p stream) nil))
                 (finish-output stream))))`

At that point, SBCL dies, no questions asked. No debugger, no LDB, no error messages, and no local core file.

MacOS SBCL will not die, but will, after the post calls start to accumulate, will run out of file descriptors and the post will fail, but SBLC lives on.

Will check out :keep-alive nil, but I believe that is the default anyway so I wasn't expressly setting that key argument.

**Comment by ajberkley** [comment]
sbcl 2.0.9 (and not 2.0.8 nor 2.0.10) had a change that made it stop ignoring sigpipe (signal delivered when one writes to a socket that the other end has closed).  Receiving sigpipe would cause sbcl to die quietly.  If you are still using 2.0.9, consider upgrading, or there is a work around to tell sbcl to ignore the sigpipe.

**Comment by ajberkley** [comment]
This should be fixed in the current (github) version of dexador.  If you have time, could you verify?

**Comment by ajberkley** [comment]
Closing as out of date --- this should not happen if you use any SBCL except 2.0.9
