### ISSUE TITLE
dex:get leaks memory

### ISSUE THREAD

**Issue by xdvom03** [fukamachi/dexador#97]
Merely running dex:get on a number of URLs without any additional settings, then not using the results for anything, causes memory usage to climb even after garbage collection is forced.

**Comment by ajberkley** [comment]
Could you retest this with the current version of dexador?  It should no longer leak sockets / memory / anything, but I would appreciate an external validation of that.

**Comment by xdvom03** [comment]
I retested and it seems that the problem is gone.
